### ISSUE TITLE
bash: compressai-vision: command not found！

### ISSUE THREAD

**Issue by bblgbr** [InterDigitalInc/CompressAI-Vision#2]
## Documentation

After installing compressai-vision, I didn’t know where to set the compressai-vision command as an executable command, so when I ran the command `compressai-vision info`, an error occurred that there was no such command. But `compressai-vision-eval --help` runs successfully. I install the whole project by docker and I install the detectron2 and JDE by myself refering to the `scripts/install.sh` and run `pip install -e . ` to install compressai-vision. This has really bothered me for a long time. It would be really ganxie if I could get a reply.

**Comment by Zr2223** [comment]
Hi, I meet the same problem as you. May I ask if you have solved it?

**Comment by bblgbr** [comment]
Yeah, I read the code and found that the `compressai-vision` command function have not been finished. So right now we could only use the `compressai-vision-eval`. I think the whole project is in development.

**Comment by fracape** [comment]
Yes, sorry about that. We have different entry points depending on the desired pipeline now:
`compressai-remote-inference` (VCM pipeline) or `compressai-split-inference` (split computing / MPEG FCM), note that `compressai-vision-eval` is kept for backward compatibility for now and corresponds to split-inference. It is meant to be deprecated soon.
