### ISSUE TITLE
There's a bug in CompressAI-Vision/utils/fcm_cttc_output_gen.py.

### ISSUE THREAD

**Issue by bblgbr** [InterDigitalInc/CompressAI-Vision#3]
## Documentation

When I run the fcm_cttc_output_gen.py. to get sfu dataset's final result, I found  the framework couldn't work successfully on `classD`. Finally, the reason I found is that the ClassD's `RaceHorses` sequence  didn't match successfully. When executing `compute_overall_mAP ` function, the 'eval_data' got the RaceHorses_832x480 sequence  RaceHorses is his prefix. Therefore I change the RaceHorses to RaceHorses_416x240 and ran successfully. I think this is a bug.

**Comment by fracape** [comment]
This was fixed in 60ce418ac078ddda889e1efea00c144891376295

**Comment by bblgbr** [comment]
Thank you！A wonderful project！
