### ISSUE TITLE
Test data download link is broken.

### ISSUE THREAD

**Issue by rohithagaram** [InterDigitalInc/CompressAI-Vision#4]
## Documentation

Hi Thanks for the code.  For the experimenting when I tried to download the dataset link is broken: https://dspub.blob.core.windows.net/mpeg-fcm/dataset/mpeg-oiv6-dataset.tar.gz

**Comment by fracape** [comment]
Good catch. Please try again and let me know.

**Comment by rohithagaram** [comment]
Thanks @fracape able to download the annotations. Meanwhile I could not find the image data where can I download it. Below example directory does not contain any images https://github.com/InterDigitalInc/CompressAI-Vision/tree/main/data/mpeg-fcm/fcm_testdata/SFU_HW_Obj/Traffic_2560x1600_30_val

**Comment by fracape** [comment]
We don't provide the datasets. As mentioned in the readmes, you can find them either from official website or the MPEG content ftp if you are MPEG member. We explain how to populate the folders to make it work with the data loaders.
